services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: p@ssw0rd1
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    volumes:
      - ./data/data:/var/opt/mssql/data
      - ./data/log:/var/opt/mssql/log
      - ./data/secrets:/var/opt/mssql/secrets


