@HostAddress = https://localhost:7078

### Health Check

GET {{HostAddress}}/health
Accept: application/json

### Create Product

POST {{HostAddress}}/products
Content-Type: application/json

{
  "name": "Product 3",
  "price": 101
}

### Get Products

GET {{HostAddress}}/products
Accept: application/json
